services:
  app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8000"
    volumes:
      - ./:/code
      - /code/.venv
      - db_data:/code/tesseracs_chat.db
      - ./jobs:/code/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: >
      sh -c "/code/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --http httptools"

# Add this section at the bottom of the file
volumes:
  db_data: